### ISSUE TITLE
Cost effectiveness of a hardware wallet

### ISSUE THREAD

**Issue by weissjeffm** [JWWeatherman/how_to_store_bitcoin#3]
If you pay $100 to secure $2000, that's a 5% cost, which many would find unacceptable, especially given the alternative of using an old computer is roughly as secure and costs nothing. 

I set the cost threshold for hardware wallet at 1% of your stash (so a $100 wallet would require $10k of bitcoin to start).

**Comment by Enegnei** [comment]
"_The alternative of using an old computer is roughly as secure and costs nothing_." An old laptop is not 'roughly as secure' as a hardware wallet in any sense. In terms of the amount of time an average person would have to spend to research, buy, and use the appropriate tools to make modifications to a laptop so that it could even be called 'secure,' the cost will easily be $100 or more.

[1] https://twitter.com/J9Roem/status/1018965131768803328
[2] https://youtu.be/wZ9LxLLvfXc

**Comment by weissjeffm** [comment]
I completely disagree. I didn't want to go into this whole issue, but since you brought it up:

You don't need to modify an old laptop AT ALL. If there's no ethernet cable plugged in, and it doesn't have any local wifi passwords, it's offline, no matter what hardware or software hacks exist.

The only question is whether an attacker could capture your seed, store it on the laptop and then exfiltrate it later. I mean, technically, yes. But I would argue that if you boot linux from USB, generate your seed, and then power off, the only attackers that have a prayer at getting your seed is either the linux distro creators, your laptop manufacturer, or Intel. The last two are basically nullified by using older hardware. The chances of them being so interested in exfiltrating bitcoin keys in 2012 for example, that they'd build in specific hardware hacks for it, is zero. Even on newer hardware I think it's foolish to even consider this a realistic attack vector. 

Now, on a hardware wallet, that's a different story  - because it's bitcoin specific, the chances that it has an exfiltration backdoor is much more likely. However, *if* the manufacturers are honest (which they likely are) the chances of a 3rd party attack are much lower than with a general purpose device like a laptop.

Personally I think the tradeoff is basically a wash: a trezor and a 5 year old laptop are equally secure for generating a seed.

Edit: if the idea is to use both - an offline laptop with a trezor to generate the seed, then yes, I agree using both together is more secure than either one alone.

**Comment by Enegnei** [comment]
1. "_You don't need to modify an old laptop AT ALL. If there's no ethernet cable plugged in, and it doesn't have any local wifi passwords, it's offline, no matter what hardware or software hacks exist._"

Old laptops are more likely to have unpatched software and firmware for WiFi functionality, and unless we are talking about a machine with [hardware kill switches](https://puri.sm/posts/hard-not-soft-kill-switches/), the average person will not be able to tell if the WiFi is truly disabled. For example, Intel was thoughtless enough to put poorly designed (especially from an authentication standpoint) remote management tech into a very large percentage of their consumer PCs, and every few months or so I'm hearing about a [new](https://mattermedia.com/blog/disabling-intel-amt/) [vulnerability](https://twitter.com/J9Roem/status/938091305883795456). It really diminishes this idea that the average laptop with a built-in software controlled Wifi card can be secure without heavy modification or complete removal.

2. "_I would argue that if you boot linux from USB, generate your seed..._"

How many non-technical or even moderately tech-savy people do you know who would know how to 1] find, download, and properly verify the integrity of a linux ISO, 2] create a Linux boot disk (hopefully on a USB that hasn't itself been compromised), 3] install and use the operating system with a compatible bitcoin wallet (keeping in the mind that distributions vary in terms of usability) and I assume 4] properly wipe that device after seed generation? This guide is supposedly intended for the average person, remember.

Also, capturing a seed you generate is not the only way your bitcoin could be compromised. There is malware that tricks you into using an existing seed / addresses that the attacker has previously generated.

3. "_The only attackers that have a prayer at getting your seed is either the linux distro creators, your laptop manufacturer, or Intel. The last two are basically nullified by using older hardware._"

Or someone who has / had physical access to that machine for even a few minutes, or someone who knows how to take advantage of any one of the boatload of known and unknown vulnerabilities that come with almost every Intel-based machine (for examples, see above).

4. "_The chances of them being so interested in exfiltrating bitcoin keys in 2012 for example, that they'd build in specific hardware hacks for it, is zero. Even on newer hardware I think it's foolish to even consider this a realistic attack vector_."

They don't have to be interested or go back in time and build specialised hardware hacks if their proprietary hardware and firmware has already been vulnerable to remote access and exfiltration for a decade or more.

4. "_Personally I think the tradeoff is basically a wash: a trezor and a 5 year old laptop are equally secure for generating a seed._."

Trust the proprietary, closed-sourced code of a general-purpose computer with a history of serious and long-term unpatched vulnerabilities... or the open-source code of a special-purpose device designed at its core to isolate key generation and prevent data exfiltration (even from a physical access standpoint), that is constantly being evaluated by a global community of researchers and engineers with a direct monetary incentive to build secure hardware. I know which one I would pick...

Finally, a 5% cost for +$2k worth of a volatile asset that (even by the most conservative estimates) is projected to massively increase in value is not too much to ask, even if you're just minimally using the hardware wallet to securely generate a seed once and then wipe it.

**Comment by weissjeffm** [comment]
All of your comments are basically irrelevant for the amounts of bitcoin this guide is targeted toward.

If you had $10 million in bitcoin then everything you said is worth worrying about, and then the expense of a hardware wallet is negligible and you should just use that.

My point is, if a hardware wallet costs 5% but the risk of a custodial account is say, only 4%, then the custodial account would be superior. You can't just ignore the HW wallet price. If you wish to avoid both costs, and you are technical enough, you can do it fairly easily with an old laptop. The costs (in risks and hardware) are negligible compared to the HW wallet and custodial accounts *given some technical knowledge*.

**Comment by Enegnei** [comment]
No, it's absolutely not irrelevant if you're thinking long-term, which is (supposedly) what the point of this guide was, and of cold storage in general. A custodial option introduces counterparty risk and that is not worth the 1% savings (at least to me).

"_If you wish to avoid both costs, and you are technical enough, you can do it fairly easily with an old laptop_."

Again, this is for the average person and most of the people even I know are not technical enough to do the process I outlined above (let alone a process that is actually good enough to be comparable to a hardware wallet) without spending several dedicated hours learning how to do it first, before implementing it. Time is a cost too.

I edited my comment before I saw yours:

_Finally, a 5% cost for +$2k worth of a volatile asset that (even by the most conservative estimates) is projected to massively increase in value is not too much to ask, even if you're just minimally using the hardware wallet to securely generate a seed once and then wipe it._

**Comment by JWWeatherman** [comment]
5% is very reasonable on the high end. Its a one time cost and not an ongoing storage cost.
