### ISSUE TITLE
Step 2 a little unclear re: offline

### ISSUE THREAD

**Issue by weissjeffm** [JWWeatherman/how_to_store_bitcoin#4]
In step 2, you say to bring up an address and then send bitcoin to it (as a test). But you should be clear that you shouldn't connect the hardware wallet to an online computer to do this (or to do the seed recovery). If you do that, you might as well not bother being offline to generate the seed.

To stay offline, you can do this, for example, by installing electrum on the offline computer (via thumb drive or whatever), connecting the wallet, and copying down the first receiving address. Then go to an online computer and send bitcoin to that address. Then use that same online computer to verify it arrived. But this is kind of iffy because you're not really verifying the hardware wallet has access to it. To do that, the hardware wallet needs to actually spend it.

**Comment by JWWeatherman** [comment]
Good point. Will clarify that the stuff needs to remain offline

**Comment by JWWeatherman** [comment]
I still haven't found a better solution for this because my target audience is non-technical. It isn't great that you have to go online to verify the funds, but its not obvious to me what it should be replaced with yet.
